### ISSUE TITLE
[BUG]Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [Harry24k/adversarial-attacks-pytorch#101]
### ✨ Short description of the bug [tl;dr]

Hi, In **adversarial-attacks-pytorch**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
scipy>=1.6.2
```

### 💬 Detailed code and results

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **scipy** can be changed to *>=0.14.0,<=1.7.3*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the scipy</summary>
 <pre>scipy.optimize.OptimizeResult
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by Harry24k** [comment]
Thank you for your reporting.
I changed the requirements following your recommendation.
https://github.com/Harry24k/adversarial-attacks-pytorch/commit/0ee4b1e9b04655e5f0f5273d19a429fc58c605d8
