### ISSUE TITLE
Regarding the title error in ./demo/Transfer Attack on CIFAR10.ipynb

### ISSUE THREAD

**Issue by Gavin-1995** [Harry24k/adversarial-attacks-pytorch#106]
Hello Harry,
Thank you for your excellent toolkit.

I have read the demo code in ./demo/Transfer Attack on CIFAR10.ipynb (https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/demo/Transfer%20Attack%20on%20CIFAR10.ipynb), and I think there might be something wrong with the title in the demo:
The transfer attack in the demo should be black box, instead of white box, I hope you can check it.

Best wishes,
Gavin

**Comment by Harry24k** [comment]
Thank you for your contribution! I fixed it: https://github.com/Harry24k/adversarial-attacks-pytorch/commit/82f09f2508e7f45eb01d3bba9b8a347e505b174b
