### ISSUE TITLE
[QUESTION] where is LGV attack?

### ISSUE THREAD

**Issue by muyuuuu** [Harry24k/adversarial-attacks-pytorch#110]
### ❔ Any questions

LGV: Boosting Adversarial Example Transferability from Large Geometric Vicinity

I can't find it in here: https://github.com/Harry24k/adversarial-attacks-pytorch/tree/master/torchattacks/attacks

**Comment by Framartin** [comment]
Hello @muyuuuu ,

The LGV attack is in `torchattacks/wrappers/lgv.py` as it can be used on top of any other attack. I implemented it as a generic wrapper to any torchattacks attack: https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/torchattacks/wrappers/lgv.py#L18 

Please don't hesitate to take a look at the [notebook dedicated to the LGV attack](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/demo/Transfer%20Attack%20combined%20with%20LGV%20on%20ImageNet.ipynb) to learn more how to use it.

I would be happy to help and answer further questions (as the first author of the paper).

Best.
