### ISSUE TITLE
[QUESTION] Why setup.py and setup.cfg be added to .gitignore?

### ISSUE THREAD

**Issue by Freed-Wu** [Harry24k/adversarial-attacks-pytorch#114]
### ❔ Any questions

<https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/.gitignore#L13-L14>

This makes user cannot install from source code.

**Comment by Framartin** [comment]
I agree. Adding those files would make testing PR code much simpler.

**Comment by Harry24k** [comment]
Sorry for the missing file. I totally have no idea that setup.py was in git ignore.
I updated it :)
