### ISSUE TITLE
[advice] use __class__.__name__

### ISSUE THREAD

**Issue by Freed-Wu** [Harry24k/adversarial-attacks-pytorch#115]
<https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/torchattacks/attack.py#L68>

```python
        self.model_name = str(model).split("(")[0]
```

is same as

```python
        self.model_name = model.__class__.__name__
```

**Comment by Harry24k** [comment]
Thank you for your advice: https://github.com/Harry24k/adversarial-attacks-pytorch/commit/fdb62912ce3bd19f3139e0277b5b3d27c8cdeea8
