### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zy899** [Harry24k/adversarial-attacks-pytorch#122]
### ✨ Short description of the bug [tl;dr]

AttributeError: 'FGSM' object has no attribute '_supported_mode'

### 💬 Detailed code and results

Everyone else meet this trouble?
I cant resolve it.
my pytorch is  1.9.0
my torchattacks is 3.3.0

**Comment by rikonaka** [comment]
You should follow the official example and submit your code here.
We can not debug without any codes.

**Comment by zy899** [comment]
Thank you very much for your reply.&nbsp;
My source code is in the attachment.&nbsp;
You can see the error by running main.py directly.&nbsp;
If you have free time, please help me to see where is the problem
Best wishes！







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Harry24k/adversarial-attacks-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Harry24k/adversarial-attacks-pytorch] [BUG] (Issue #122)





 
You should follow the official example and submit your code here.
 We can not debug without any codes.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Adversarial-Attack-on-Machinery-Fault-Diagnosis-main (2).zip (60.13M, 2023年04月08日 20:40 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=4462643628bd04ca7c8be00f10660b194d16515255025b54180157540e4b0e53005b49030e555f1b0d55500554560b5706555604365a39775114014445074b5f540e4977421258555e4f0b581b2b58555d0b0a53441f1470541708421b225057520c0b455f15145b540b0a161e5410184f0b14360b&code=5bd66f96

**Comment by rikonaka** [comment]
> 

The API that you are using is very old, so a lot of the methods are just gone. 🤪
