### ISSUE TITLE
AttributeError: 'PGD' object has no attribute '_supported_mode'

### ISSUE THREAD

**Issue by zy899** [Harry24k/adversarial-attacks-pytorch#125]
### ✨ Short description of the bug [tl;dr]

Have any of you encountered the same problem?

### 💬 Detailed code and results

`atk = am.attack().get(name, model, args.params)`
`if args.targeted:`
`if 'target' not in atk._supported_mode:`
           
When I wrote the third line, the error was reported as shown in the title

**Comment by rikonaka** [comment]
Hi @zy899 if you want to make a targeted attack, do as this code.
```
from torchattacks import PGD
atk = PGD(model, eps=8/255, alpha=2/255, steps=10, random_start=True)
atk.set_mode_targeted_least_likely(kth_min)
adv_images = atk(images, labels)
```

**Comment by zy899** [comment]
`class attack():
    def get(self,name,model,params):
        atk=None
        if name == "fgsm":
            atk = ta.FGSM(model, eps=params['fgsm_eps'])
        elif name == "pgd":
            atk = ta.PGD(model, eps=params['pgd_eps'],alpha=params['pgd_alpha'], steps=params['pgd_steps'],random_start=params['pgd_random_start'])
        # elif name == "deepfool":
        #     atk=ta.DeepFool(model,steps=params['deepfool_steps'],overshoot=params['deepfool_overshoot'])
        # elif name == "cw":
        #     atk=ta.CW(model,c=params['cw_c'], kappa=params['cw_kappa'],steps=params['cw_steps'],lr=params['cw_lr'])
        else:
            raise Exception('no such attackMethod choice')
        return atk`

**Comment by zy899** [comment]
I'm sorry that I didn't post all my code just now, so you can't see it clearly. Below is the part of my error code and where I define the method myself.

![1678366086729](https://user-images.githubusercontent.com/81020181/224027463-2ba2efc1-789c-4142-bec0-cdec6f275a66.png)
![1678366132020](https://user-images.githubusercontent.com/81020181/224027632-9f828689-873d-48c3-9ea5-88a7361a43d8.png)

**Comment by rikonaka** [comment]
> I'm sorry that I didn't post all my code just now, so you can't see it clearly. Below is the part of my error code and where I define the method myself.
> 
> ![1678366086729](https://user-images.githubusercontent.com/81020181/224027463-2ba2efc1-789c-4142-bec0-cdec6f275a66.png) ![1678366132020](https://user-images.githubusercontent.com/81020181/224027632-9f828689-873d-48c3-9ea5-88a7361a43d8.png)

If you download this code from internet, maybe you should go back use version [v3.0.0](https://github.com/Harry24k/adversarial-attacks-pytorch/releases/tag/v3.0.0) or [v2.10.2](https://github.com/Harry24k/adversarial-attacks-pytorch/releases/tag/v2.10.2), the most newest version is makes many changes.
