### ISSUE TITLE
Regression case[QUESTION]

### ISSUE THREAD

**Issue by dheerajvarma24** [Harry24k/adversarial-attacks-pytorch#128]
### ❔ Any questions

Can we extend this code to the Regression case where we have several continuous inputs and the output belongs to R (real numbers)? If so how?

At the moment, I see this code is valid for only classification cases.

**Comment by Harry24k** [comment]
Currently, attacks are constructed only for the classification task.
For the regression case, we need to fix more than one part of the codes.
It will be a huge update, so I will move it to an issue for future work.
Thank you!

**Comment by dheerajvarma24** [comment]
@Harry24k Thank you for the immediate reply. If there's any plan to incorporate regression cases in near future, I am happy to contribute, please let me know your timeline in such case.
