### ISSUE TITLE
[QUESTION] run  Pixel attack error

### ISSUE THREAD

**Issue by Jiang010** [Harry24k/adversarial-attacks-pytorch#129]
### ❔ Any questions

When I run the Pixel attack, I get the error message 'RuntimeError: shape '[-1, 6]' is invalid for input of size 9'. 
I suspect this error is coming from the '_perturb' function in 'pixle .py'.
```
def _perturb(self, source, solution, destination=None):
      .....
        s = source[0][source_pixels].view(3, -1)
        destination[0, :, indexes[:, 0], indexes[:, 1]] = s

        return destination

```
In the code, ```s = source[0][source_pixels].view(3, -1) ```
I am not sure why the argument ```3``` is used.
Therefore, I am attempting to fix this error by trying out a modified of the code.
```
def _perturb(self, source, solution, destination=None):
      .....python
        # s = source[0][source_pixels].view(3, -1)
        tmp = (destination[0, :, indexes[:, 0], indexes[:, 1]].shape)[0]
        s = source[0][source_pixels].view(tmp, -1)
        destination[0, :, indexes[:, 0], indexes[:, 1]] = s

        return destination
```

But I am not sure if this modified version is correct. 
If there are any errors, please let me know.  
Thank you.

**Comment by Harry24k** [comment]
Sorry for the typo. 
I changed it to `s = source[0][source_pixels].view(c, -1)`.
Thank you for your contribution!
