### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zylprivate** [Harry24k/adversarial-attacks-pytorch#136]
### ✨ Short description of the bug [tl;dr]

In latest version, if I use set_normalization_used, I will get the error following: ValueError: Input must have a range [0, 1] (max: 1.0, min: -2.9802322387695312e-08).
In previous version, it works well.
I think the normalization and inverse normalization can't recover distribution [0,1] precisely owing to floating point number.
 

### 💬 Detailed code and results

I use cifar10 to train.
The mean and std I used is listed as followed:
mean = {
    'cifar10': (0.4914, 0.4822, 0.4465),

}
std = {
    'cifar10': (0.2023, 0.1994, 0.2010),
}
I also set use set_normalization_used function.
`        atk = torchattacks.PGD(net,eps=8/255, alpha=2/255, steps=1,random_start=True) `
`       atk.set_normalization_used(mean=mean[args.dataset],std=std[args.dataset])`
`		adv_images = atk(input,target)`

**Comment by rikonaka** [comment]
Hi @zylprivate , I have submitted a fix for this bug, but you can still use the previous torchattacks version until it is accepted.

**Comment by zylprivate** [comment]
Thank you very much.
