### ISSUE TITLE
Ragarding the attacking mode in Class Attack.

### ISSUE THREAD

**Issue by tao-bai** [Harry24k/adversarial-attacks-pytorch#14]
Hi Harry, I see the below codes and feel a little confused.
When performing untargeted attacks, `self._targeted = 1`
```
cost = self._targeted*loss(outputs, labels)
grad = torch.autograd.grad(cost, images,retain_graph=False, create_graph=False)[0]
adv_images = images + self.eps*grad.sign()
```
Is it easier to understand to set `self._targeted = -1` for untargeted attacks?
and modify corresponding lines 
```
cost = self._targeted*loss(outputs, labels)
grad = torch.autograd.grad(cost, images,retain_graph=False, create_graph=False)[0]
adv_images = images - self.eps*grad.sign()
```

**Comment by Harry24k** [comment]
Thank you for your suggestion. 
It seems to have been implemented in that way in order not to change much of the existing code when adding the targeted mode.
I think it would be better to change it.

**Comment by Harry24k** [comment]
Updated!

https://github.com/Harry24k/adversarial-attacks-pytorch/commit/80e3741f5e8cad39ac31084ed08c2a60143560c0
