### ISSUE TITLE
[QUESTION] Can be used for segmentation tasks?

### ISSUE THREAD

**Issue by MarlonGarcia** [Harry24k/adversarial-attacks-pytorch#141]
### Please, this library can be used for segmentation tasks?

If yes, what will be the size and content of `label` when the attack function is called (as seen below)?

Will it be `(N, H, W)` ?

```
atk = torchattacks.PGD(model, eps=8/255, alpha=1/255, steps=10)
image_adv = atk(image, label)
```

**Comment by rikonaka** [comment]
Hi @MarlonGarcia , please describe what your input shape is, and explain what your purpose is. The information you provided is too little for us to give a specific reply.

**Comment by MarlonGarcia** [comment]
I am trying to set the adversarial attacks for a segmentation task. First, I defined the 'random target' mode:

```
atk = torchattacks.PGD(model, eps=8/255, alpha=2/255, steps=10)
atk.set_mode_targeted_random()
```

Then I think I have to pass the true label to make `atk` to calculate the right adversarial example, don't I? So I used:

```
for data in loader:
    image, target = data
    image_adv = atk(image, target)
```

But it rises the error:
```
  File "C:\Users\marlo\anaconda3\envs\environment\lib\site-packages\torchattacks\attack.py", line 434, in get_random_target_label
    l.remove(labels[counter])

RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

**Comment by MarlonGarcia** [comment]
I am trying to set the adversarial attacks for a segmentation task. First, I defined the 'random target' mode:

```
atk = torchattacks.PGD(model, eps=8/255, alpha=2/255, steps=10)
atk.set_mode_targeted_random()
```

Then I think I have to pass the true label to make `atk` to calculate the right adversarial example, don't I? So I used:

```
for data in loader:
    image, target = data
    image_adv = atk(image, target)
```

But it rises the error:
```
  File "C:\Users\marlo\anaconda3\envs\environment\lib\site-packages\torchattacks\attack.py", line 434, in get_random_target_label
    l.remove(labels[counter])

RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

**Comment by rikonaka** [comment]
Hi @MarlonGarcia , very strange error, I can't reproduce this error at all.

Can you show the shape of your `image` and `label` variable?

```python
for data in loader:
    image, label = data
    print(image.shape)
    print(label.shape)
    # image_adv = atk(image, label)
```

![image](https://user-images.githubusercontent.com/13602602/233794767-a0a61358-dbff-4882-8b1f-1e5f5be1c067.png)
