### ISSUE TITLE
[FEATURE] Consider adding PI-FGSM attack

### ISSUE THREAD

**Issue by CHENBIN99** [Harry24k/adversarial-attacks-pytorch#143]
### ✨ Short description of the feature [tl;dr]

Thanks for your great contributions!

This library contains many types of attack methods. Here I suggest adding the **PI-FGSM** method to the library. Links to papers and open source codes related to the method are as follows:

[paper](https://arxiv.org/abs/2007.06765)
[code](https://github.com/qilong-zhang/Patch-wise-iterative-attack)

This method uses patch-wise perturbation to attack the model, and the adversarial examples generated by it have good attack transferability.

### 💬 Detailed motivation and codes

[paper](https://arxiv.org/abs/2007.06765)
[code](https://github.com/qilong-zhang/Patch-wise-iterative-attack)

**Comment by rikonaka** [comment]
Hi @CHENBIN99 , thanks for the suggestion, I have submitted new [code](https://github.com/Harry24k/adversarial-attacks-pytorch/pull/144) for the new PI-FGSM attack, it won't take long before you can use PI-FGSM in torchattacks.

**Comment by CHENBIN99** [comment]
Thank you for your fast and efficient work!

As for the target attack, it is possible that the author did not implement this function, and I have not found a description or code for the implementation of the target attack, but in any case, it is good enough to implement a non-target attack.

I will continue to follow the progress of the `torchattacks` library!
