### ISSUE TITLE
[BUG]when i use pip to install the new version, it uinstall my cuda and torch(1.12.0) and install the cpu version(1.13.0)

### ISSUE THREAD

**Issue by biuboomc** [Harry24k/adversarial-attacks-pytorch#157]
### ✨ Short description of the bug [tl;dr]

it's all right for update version, but why the cpu version.

### 💬 Detailed code and results

Is it the atk's problem or the pip's?

**Comment by rikonaka** [comment]
Hi @biuboomc , could you provide your command and its output?

**Comment by biuboomc** [comment]
The command was just pip install torchattacks, but strangely enough I removed and installed the package again to get the output, but this time nothing went wrong. Maybe there was something wrong with my local environment last time. Anyway, thanks for your reply.
