### ISSUE TITLE
[BUG] no function "set_training_mode" but "set_model_training_mode" instead

### ISSUE THREAD

**Issue by skadiscarlet** [Harry24k/adversarial-attacks-pytorch#159]
### ✨ Short description of the bug [tl;dr]

no such function name "set_training_mode" in the base model "attack" ([func](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/3c8e03fdf6688bfa4e4ebfc6a63762df0ad258b0/torchattacks/attack.py#L222)). So some mistakes occure in the [README.md()](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/3c8e03fdf6688bfa4e4ebfc6a63762df0ad258b0/README.md?plain=1#L137) and the wrapper [LGV()](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/3c8e03fdf6688bfa4e4ebfc6a63762df0ad258b0/torchattacks/wrappers/lgv.py#L150).

### 💬 Detailed code and results

.

**Comment by skadiscarlet** [comment]
> Hi @skadiscarlet , yes, that's mistakes, I will fix that.

also method "set_return_type" dosen't exist in class Attack too. And the wrapper LGV use it ( [set_return_type](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/3c8e03fdf6688bfa4e4ebfc6a63762df0ad258b0/torchattacks/wrappers/lgv.py#L164)). In fact, there is nothing assign to self.return_type.

**Comment by rikonaka** [comment]
> > Hi @skadiscarlet , yes, that's mistakes, I will fix that.
> 
> also method "set_return_type" dosen't exist in class Attack too. And the wrapper LGV use it ( [set_return_type](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/3c8e03fdf6688bfa4e4ebfc6a63762df0ad258b0/torchattacks/wrappers/lgv.py#L164)). In fact, there is nothing assign to self.return_type.

Ok, I will fix that as soon as possible. 😜
