### ISSUE TITLE
Adversarial Training

### ISSUE THREAD

**Issue by COD1995** [Harry24k/adversarial-attacks-pytorch#169]
### ❔ Any questions

Is there a demo of how to do adversarial training using this library?

**Comment by rikonaka** [comment]
> ### ❔ Any questions
> 
> Is there a demo of how to do adversarial training using this library?

Well, you can check the Harry's new project https://github.com/Harry24k/MAIR/ , this library is about adversarial training. 👍

**Comment by COD1995** [comment]
Thanks a lot much appreciated
