### ISSUE TITLE
One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

### ISSUE THREAD

**Issue by rishiyanth** [Harry24k/adversarial-attacks-pytorch#170]
### ✨ Short description of the bug [tl;dr]

The above RunTimeError arises when I am trying to perform torchattack on my custom convolutional layer. 
It expects allow_unused=True to be set in torch.autograd.grad of the package file

### 💬 Detailed code and results

RuntimeError                              Traceback (most recent call last)
[<ipython-input-39-54e9eb1b62ea>](https://localhost:8080/#) in <cell line: 1>()
----> 1 perform_attack(QCNN)

3 frames
[<ipython-input-38-f943f2c85389>](https://localhost:8080/#) in perform_attack(model)
     43 
     44     #PGD attack
---> 45     adversarial_pgd = attack_pgd(image, label)
     46     y_pred_pgd = model1(adversarial_pgd)
     47     y_pred_pgd = y_pred_pgd.argmax(dim=1)

[/usr/local/lib/python3.10/dist-packages/torchattacks/attack.py](https://localhost:8080/#) in __call__(self, inputs, labels, *args, **kwargs)
    509             self._set_normalization_applied(True)
    510         else:
--> 511             adv_inputs = self.forward(inputs, labels, *args, **kwargs)
    512             # adv_inputs = self.to_type(adv_inputs, self.return_type)
    513 

[/usr/local/lib/python3.10/dist-packages/torchattacks/attacks/pgd.py](https://localhost:8080/#) in forward(self, images, labels)
     70 
     71             # Update adversarial images
---> 72             grad = torch.autograd.grad(
     73                 cost, adv_images, retain_graph=False, create_graph=False
     74             )[0]

[/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py](https://localhost:8080/#) in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused, is_grads_batched, materialize_grads)
    392         )
    393     else:
--> 394         result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    395             t_outputs,
    396             grad_outputs_,

RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

**Comment by rikonaka** [comment]
Hi @rishiyanth , can you provide a working test code for me for debug?

**Comment by rishiyanth** [comment]
Ok, let me try that out. Thank you!
