### ISSUE TITLE
Hope torchattack can add using model predictions as ground truth to avoid label leaking.

### ISSUE THREAD

**Issue by leejiajun** [Harry24k/adversarial-attacks-pytorch#19]
Hope can add using model predictions as ground truth to avoid label leaking.

**Comment by Harry24k** [comment]
I suggest using `set_mode_least_likely(kth_min=1)`.
This makes the attack uses the prediction of the model as the label to be used in attack.
e.g. `atk = torchattacks.FGSM(model, eps=8/255)
atk.set_mode_least_likely()`

**Comment by leejiajun** [comment]
Sounds good. What does this function aim originally to solve? I read your paper, "Torchattacks: A PyTorch Repository for Adversarial Attacks", but I didn't find its description.

**Comment by Harry24k** [comment]
In the paper, the detailed methods are omitted. Please refer to [the documentation](https://adversarial-attacks-pytorch.readthedocs.io/en/latest/attack.html#torchattacks.attack.Attack.set_mode_least_likely).

p.s. `set_mode_least_likely(kth_min)` is a function for using an index of the k-th minimum value in the output vector of the model as the target label.

**Comment by leejiajun** [comment]
Thank you.
