### ISSUE TITLE
[QUESTION] using torchattacks on HuggingFace transformer models

### ISSUE THREAD

**Issue by bakachan19** [Harry24k/adversarial-attacks-pytorch#193]
### ❔ Any questions

Hi, 
I was wondering if is possible to use this library to attack  Huggingface transformer models, for example the vit-base-patch16-224 model. 
If so, could you provide a demo code for doing this? 

Thank you.
Have a great day!

**Comment by rikonaka** [comment]
First, all of torchattacks' current attack algorithms are not designed for ViT, so their performance on ViT is unknown and uncertain.

Secondly, if you want to use torchattacks to attack ViT, just make sure that the inputs and outputs of your model match the requirements.

> model input: (N, C, H, W)
> model output: (N, num_of_class)

![Example](https://github.com/Harry24k/adversarial-attacks-pytorch/assets/13602602/8bc1cffb-5a48-4aa3-bf56-8d21e0b5aaf1)

Here is the code I tested on imagenet, you can refer to it (PS: my tests found that the FGSM attack had a success rate of no more than 80%).

```python
import torch
from torchvision.models import vision_transformer, ViT_B_16_Weights
from torchvision import datasets, transforms
from torchattacks import FGSM
from tqdm import tqdm

model = vision_transformer.vit_b_16(weights=ViT_B_16_Weights.IMAGENET1K_V1)
device = torch.device('cuda')
model = model.to(device)

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])

transform_test = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    normalize,
])

testset = datasets.ImageNet(
    root='./data', split='val', transform=transform_test)

test_loader = torch.utils.data.DataLoader(
    testset, batch_size=10, shuffle=False, num_workers=8)

total = 0
total_success = 0
model.eval()
atk = FGSM(model)
atk.set_normalization_used(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])

print('start attack...')

pbar = tqdm(total=len(test_loader))
for (images, labels) in test_loader:
    images, labels = images.to(device), labels.to(device)

    adv_images = atk(images, labels)
    adv_pred = model(adv_images)
    success = torch.sum(labels != torch.argmax(adv_pred, 1))
    total_success += success
    total += images.shape[0]
    pbar.set_description(
        "attack success rate {:.1f}".format(total_success / total * 100.0))
    pbar.update()

success_rate = total_success / total
print("Attack success rate: {:.3f}".format(success_rate))
```

**Comment by bakachan19** [comment]
Dear @rikonaka,
Thank you for your reply and help.
I will play around with some models and see how the testing goes.

Have a great day!
