### ISSUE TITLE
The problem of torchattack package

### ISSUE THREAD

**Issue by manwu1994** [Harry24k/adversarial-attacks-pytorch#23]
Hello, I try yo apply this package on my model and it reports this problem, could you give me any suggestions to revise it? Thank you for your time.
```
  File "white_box_attack.py", line 1070, in <module>
    adv_images = atk(images, labels)
  File "/home/wuman/.local/lib/python3.6/site-packages/torchattacks/attack.py", line 249, in __call__
    images = self.forward(*input, **kwargs)
  File "/home/wuman/.local/lib/python3.6/site-packages/torchattacks/attacks/pgd.py", line 62, in forward
    retain_graph=False, create_graph=False)[0]
  File "/home/wuman/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 225, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.
```

**Comment by Harry24k** [comment]
Can you attach the whole files?

**Comment by manwu1994** [comment]
Oh, sorry! I try to use the package in my custom model with surrogate gradients, maybe it will cause this problem. I try to improved the atk based on your source code!! Thanks a lot!

**Comment by manwu1994** [comment]
But, I have another problem " No module named 'scipy._lib.six". Is the version problem? I can running previous and I have scipy and six paackage. Thank you
