### ISSUE TITLE
device not same problem.

### ISSUE THREAD

**Issue by RocketWhite** [Harry24k/adversarial-attacks-pytorch#3]
Hello Harry,
Thanks for your code.
Here’s the situation I meet:
My server has two gpus, which are cuda: 0 and cuda: 1. However, if I send my model to cuda: 1, then attack would change it to cuda: 0 instead.

Code is here:
torchattacks/attack.py line 20
self.device = torch.device("cuda" if next(model.parameters()).is_cuda else "cpu")

Could it be okay to change it to:
self.device = next(model.parameters()).device

I test the code based on torch=1.4.0
This could help me maintain the same device in both my model and datasets.
Thanks a lot.

Ruqi Bai

**Comment by Harry24k** [comment]
Since I only use one GPU, I wasn't thinking about the problem at all.
I modified code as you suggested and checked there is no errors on demos.
Please check version 1.2!
Thank you.
Harry

**Comment by RocketWhite** [comment]
Hi,
Thanks for your quick reply and update. Here's one same problem in torchattacks.py line: 30. 
I don't find this file in the source code. But I do have one file in my package. (I use pip to import your package)

**Comment by Harry24k** [comment]
Sorry, I mixed it up with the previous versions and uploaded it.
Please upgrade once again to version 1.3.
Thanks a lot.
