### ISSUE TITLE
Error on Running the Cifar10 demo jynb

### ISSUE THREAD

**Issue by tee2015** [Harry24k/adversarial-attacks-pytorch#30]
Hello ,

I am running the cifar10 demo and I am having this error once I load the model.pth checkpoint saved.

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-d95678798e8a> in <module>
----> 1 model.load_state_dict(torch.load("/home/jovyan/.cache/torch/checkpoints/resnext50_32x4d-7cdf4587.pth"))
      2 model = model.eval()

/srv/conda/envs/notebook/lib/python3.7/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    828         if len(error_msgs) > 0:
    829             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 830                                self.__class__.__name__, "\n\t".join(error_msgs)))
    831         return _IncompatibleKeys(missing_keys, unexpected_keys)
    832 

RuntimeError: Error(s) in loading state_dict for Target:
	Missing key(s) in state_dict: "conv_layer.0.weight", "conv_layer.0.bias", "conv_layer.1.weight", "conv_layer.1.bias", "conv_layer.4.weight", "conv_layer.4.bias", "conv_layer.5.weight", "conv_layer.5.bias", "conv_layer.7.weight", "conv_layer.7.bias", "conv_layer.8.weight", "conv_layer.8.bias", "conv_layer.11.weight", "conv_layer.11.bias", "conv_layer.12.weight", "conv_layer.12.bias", "conv_layer.14.weight", "conv_layer.14.bias", "conv_layer.15.weight", "conv_layer.15.bias", "conv_layer.18.weight", "conv_layer.18.bias", "conv_layer.19.weight", "conv_layer.19.bias", "conv_layer.21.weight", "conv_layer.21.bias", "conv_layer.22.weight", "conv_layer.22.bias", "conv_layer.24.weight", "conv_layer.24.bias"

Thank you in advance :)

**Comment by Harry24k** [comment]
It seems the error occurred during the model loading process.
Please use proper model structure and state_dict.

**Comment by tee2015** [comment]
Hi Harry,

I have been working on enhancing the save of my model after training and validating,
this is what i am using to save my model,
torch.save({#'model_state_dict': model,
                    #added new
                    'model_state_dict': model.state_dict(),
                    }, os.path.join(self.checkpoint, 'model_{}.pth'.format(task_id)))

however, I am still not able to load the model into adversarial attack PyTorch.

**Comment by Harry24k** [comment]
From what you wrote, I can't tell what the problem is. Can you tell me more?

**Comment by tee2015** [comment]
My bad sorry, let me explain further, I am saving my model as above and trying to load it with the Cifar 10 jupyter note demo example however I am still facing the same error `Loading state_dict `. 
There is one approach that I am going to try and update my issue here. I hope this might solve my problem by saving my model with a key.

**Comment by tee2015** [comment]
Ok, I trained my model and save it as pth then open the demo cifar notebook and try to load my model and perform the same attack provided.
Now I am able to save all the model after first save I load the checkpoint I have a one error related to a net object I was using it while I saved the model however , it seems I am able to run a PGD attack now, I will test the model with other notebooks and explore the attack platform more. Thank you @Harry24k
