### ISSUE TITLE
Question about perturbation PGD

### ISSUE THREAD

**Issue by wuyuuu** [Harry24k/adversarial-attacks-pytorch#37]
Hello,

Firstly thanks for your great work!

I have a question about `eps` in `atk = torchattacks.PGD(model, eps=8/255, alpha=2/255, steps=4)`

It is showed that `eps (float): maximum perturbation. (DEFALUT : 0.3)`.

So I want to know does that mean `eps` = maximal l-infinity norm of `adv - img` ? cuz I've run some experiments by PGD and the l-infity norm I calculated significantly exceeded the `eps` value.

So I really want to know is it because I got some mistakes in my calculation ? or `eps: the maximal  perturbation` has some different meaning

**Comment by Harry24k** [comment]
Hello,

Thank you for using torchattacks!

As you mentioned, `eps = maximal l-infinity norm of adv - img` is right. PGD outputs cliped images with epsilon l-inf distance: https://github.com/Harry24k/adversarial-attacks-pytorch/blob/cf21e81f3f2e7a859e029e3d7953290ef063d6dd/torchattacks/attacks/pgd.py#L74

If you want to check it out, we can use https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/demos/Performance%20Comparison%20(CIFAR10).ipynb as follows:
`torch.norm(advl_images - images, p=float('inf'), dim=[1,2,3], keepdim=False, out=None, dtype=None)`

**Comment by wuyuuu** [comment]
> Hello,
> 
> Thank you for using torchattacks!
> 
> As you mentioned, `eps = maximal l-infinity norm of adv - img` is right. PGD outputs cliped images with epsilon l-inf distance:
> 
> https://github.com/Harry24k/adversarial-attacks-pytorch/blob/cf21e81f3f2e7a859e029e3d7953290ef063d6dd/torchattacks/attacks/pgd.py#L74
> 
> If you want to check it out, we can use https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/demos/Performance%20Comparison%20(CIFAR10).ipynb as follows:
> `torch.norm(advl_images - images, p=float('inf'), dim=[1,2,3], keepdim=False, out=None, dtype=None)`

Thanks for your reply !

I've found the mistake in my code 😂, so now it works fine for me
