### ISSUE TITLE
What does w.detach_() do in cw.py?

### ISSUE THREAD

**Issue by HeekangPark** [Harry24k/adversarial-attacks-pytorch#4]
Hi, I'm a newbie just started to study adversarial examples.

I'm curious what does `w.detach_()`(line 76)  do in `torchattacks/attacks/cw.py`?

I think torch should record all operation applied to w.

**Comment by Harry24k** [comment]
```
w = torch.zeros_like(images).to(self.device)
w.detach_()
w.requires_grad=True
```

In the above lines, ```w.detach_()``` is just for double check to confirm w is not dependent on images. In line 77, with ```w.requires_grad=True``` we record all operation after the initialization (line 75-75).
