### ISSUE TITLE
Does OnePixel support targeted attack?

### ISSUE THREAD

**Issue by WuTao18** [Harry24k/adversarial-attacks-pytorch#47]
![image](https://user-images.githubusercontent.com/32795326/141065321-9e736a0b-3432-4a13-9d0d-3e3cd1a7a6ff.png)

![image](https://user-images.githubusercontent.com/32795326/141065490-f77bcab6-15d4-4f88-8765-75ce4632aa48.png)

**Comment by Harry24k** [comment]
Yet, I've not evaluated the performance of the targeted mode of Onepixel attack. Soon it will be added.

**Comment by Harry24k** [comment]
Updated! (https://github.com/Harry24k/adversarial-attacks-pytorch/commit/2fa60aaed4378258701525cf41c5855a5d165f51)
