### ISSUE TITLE
Device error 

### ISSUE THREAD

**Issue by Aminullah6264** [Harry24k/adversarial-attacks-pytorch#49]
Hi Harry

I just tried with the demo code, however it pop up the following error. 

torchattacks/attack.py", line 26, in __init__
    self.device = next(model.parameters()).device
StopIteration:

**Comment by Aminullah6264** [comment]
solved by the following change in attack.py file
```
#     self.device = next(model.parameters()).device
       self.device = 'cuda'
```

**Comment by Aminullah6264** [comment]
self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

**Comment by Harry24k** [comment]
This can be work, but I worried about the case you use more than 1 GPUs.
