### ISSUE TITLE
How to Change Distance Measure in FGSM

### ISSUE THREAD

**Issue by Aminullah6264** [Harry24k/adversarial-attacks-pytorch#50]
Hi harry, 

I have run the FGSM with default distance measure Linf. I can see there is PGDL2 class, however, I couldn't find FGSML2, How can I change it to L2 norm.

**Comment by Harry24k** [comment]
You can use FGSML2 by setting `steps=1` and `eps=alpha`.
For example,
`atk = PGDL2(model, eps=eps, alpha=eps, steps=1, random_start=True, eps_for_division=1e-10)`
