### ISSUE TITLE
Query about PGD code

### ISSUE THREAD

**Issue by motoight** [Harry24k/adversarial-attacks-pytorch#53]
pdg attack code in[ here](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/torchattacks/attacks/pgdl2.py#L80) it's kind of confusing and useless

**Comment by Harry24k** [comment]
Here, `delta` is calculated for l2-norm projection on the \epsilon-ball of the original image.
Could you tell me a better suggestion?
