### ISSUE TITLE
Advice for calculating the time in demo code

### ISSUE THREAD

**Issue by Harr7y** [Harry24k/adversarial-attacks-pytorch#58]
Firstly, thanks for the nice contributions.

I have a little advice for your demo code :

https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/demos/White%20Box%20Attack%20(ImageNet).ipynb

The third part:3. Adversarial Attack
in the loop
"
for images, labels in data_loader:
start = time.time()
……
"
I think 'start' should be outside of the loop. I know the demo only have an image in the dataset, but when I apply it to other common datasets with batch size larger than 1, it may lead to some confusion.

**Comment by Harry24k** [comment]
Thank you. I fixed the demo. 😄
