### ISSUE TITLE
Why the attacking methods are finally clamping the pixel values to [0,1]? 

### ISSUE THREAD

**Issue by futakw** [Harry24k/adversarial-attacks-pytorch#6]
Some models may input normalized images that will have some negative pixel values.
Is there any reason that you are not supposing the normalized images to be attacked? 

I want to try this code for a model that inputs normalized images.

**Comment by Harry24k** [comment]
Please refer https://github.com/Harry24k/adversarial-attacks-pytorch/issues/1.

**Comment by futakw** [comment]
Thanks.
