### ISSUE TITLE
PiPy only have the version of 3.2.5

### ISSUE THREAD

**Issue by CHENBIN99** [Harry24k/adversarial-attacks-pytorch#64]
I want to install the version of 3.2.6 to solve #61 , but I found there only have 3.2.5 in https://pypi.org/project/torchattacks/ , I found the source code of 3.2.6, but I do not kown how to install from the source code, because the file of setup.py was missed.

**Comment by Harry24k** [comment]
Sorry for the delay.
Please check https://pypi.org/project/torchattacks/
