### ISSUE TITLE
some error.

### ISSUE THREAD

**Issue by byerose** [Harry24k/adversarial-attacks-pytorch#80]
[difgsm.py](https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/torchattacks/attacks/difgsm.py)

>     Examples::
>         >>> attack = torchattacks.DI2FGSM(model, eps=8/255, alpha=2/255, steps=20, decay=0.0, resize_rate=0.9, diversity_prob=0.5, random_start=False)
>         >>> adv_images = attack(images, labels)

should be `attack = torchattacks.DIFGSM(...)`

**Comment by Harry24k** [comment]
Thank you for your comment!
