### ISSUE TITLE
How to use the atk.save

### ISSUE THREAD

**Issue by Cassiatora** [Harry24k/adversarial-attacks-pytorch#82]
Hi,  atk.save(data_loader, save_path="./data/sample.pt", verbose=True). The data_loader is ori_dataloader or attack_dataloader?

**Comment by Harry24k** [comment]
In `atk.save(data_loader, save_path="./data/sample.pt", verbose=True)` , data_loader, which is passed as an argument, should be a data loader that will be attacked.
