### ISSUE TITLE
FAB targeted=True

### ISSUE THREAD

**Issue by guanhdrmq** [Harry24k/adversarial-attacks-pytorch#92]
Hi, when running the white box attack, the FAB outputs are total printed by targeted= false. Can you please double check it?
Thank you very much

**Comment by Harry24k** [comment]
Currently, single-targeted mode for FAB is not supported.
The `targeted` argument of FAB is only for multi-targeted mode.
Thank you for your suggestion.

**Comment by guanhdrmq** [comment]
Hi Harry,

No problem.

I found you have not added JSMA attack in the library. That would be wonderful if you wanna add it.

Cheers
Jiwei

















Jiwei (Wayne) Guan

Research Assistant  & Casual Academic| Intelligent Systems Research Center

Department of Computing | Level 3 Becton-Dickinson (BD) Building

4 Research Park Drive | Macquarie University, NSW 2109, Australia

W: http://itseg.org<http://itseg.org> | M: +61 0423553353 |  P: https://www.linkedin.com/in/jiwei-guan/

[cid:b8e83bc9-acf5-4373-80dc-ad508ec5e7b5]<https://www.mq.edu.au/>
________________________________

**Comment by Harry24k** [comment]
Now, FAB supports `targeted mode`.
Please refer to https://github.com/Harry24k/adversarial-attacks-pytorch/commit/8b35fb59b7447b9adf4ce8b7fa9fc8b2f9d637f4.

**Comment by guanhdrmq** [comment]
Hi Harry,

No problem.

I found you have not added JSMA attack in the library. That would be wonderful if you wanna add it.
Thank for your FAB supports
